CREATE TABLE "asset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "asset_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"facilityId" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"type" varchar(100) NOT NULL,
	"status" varchar(50) DEFAULT 'online' NOT NULL,
	"description" text,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp
);
--> statement-breakpoint
CREATE TABLE "facility" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "facility_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"location" varchar(512),
	"description" text,
	"createdAt" timestamp NOT NULL,
	"updatedAt" timestamp
);
--> statement-breakpoint
CREATE TABLE "sensor_reading" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sensor_reading_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assetId" integer NOT NULL,
	"metricName" varchar(100) NOT NULL,
	"value" real NOT NULL,
	"unit" varchar(50) NOT NULL,
	"timestamp" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "asset" ADD CONSTRAINT "asset_facilityId_facility_id_fk" FOREIGN KEY ("facilityId") REFERENCES "public"."facility"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sensor_reading" ADD CONSTRAINT "sensor_reading_assetId_asset_id_fk" FOREIGN KEY ("assetId") REFERENCES "public"."asset"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "asset_facility_idx" ON "asset" USING btree ("facilityId");--> statement-breakpoint
CREATE INDEX "asset_name_idx" ON "asset" USING btree ("name");--> statement-breakpoint
CREATE INDEX "asset_type_idx" ON "asset" USING btree ("type");--> statement-breakpoint
CREATE INDEX "asset_status_idx" ON "asset" USING btree ("status");--> statement-breakpoint
CREATE INDEX "facility_name_idx" ON "facility" USING btree ("name");--> statement-breakpoint
CREATE INDEX "reading_asset_idx" ON "sensor_reading" USING btree ("assetId");--> statement-breakpoint
CREATE INDEX "reading_timestamp_idx" ON "sensor_reading" USING btree ("timestamp");--> statement-breakpoint
CREATE INDEX "reading_metric_idx" ON "sensor_reading" USING btree ("metricName");--> statement-breakpoint
CREATE INDEX "reading_asset_timestamp_idx" ON "sensor_reading" USING btree ("assetId","timestamp");--> statement-breakpoint
CREATE INDEX "reading_asset_metric_idx" ON "sensor_reading" USING btree ("assetId","metricName");